box_themes = {
	'default': {
		'upper_border': "─",
		'lower_border': "─",
		'left_border': "│",
		'right_border': "│",
		'horizontal_line': "─",
		'vertical_line': "│",
		'full_intersection': "┼",
		'left_vertical': "├",
		'right_vertical': "┤",
		'upper_horizontal': "┬",
		'lower_horizontal': "┴",
		'upper_left': "┌",
		'upper_right': "┐",
		'lower_left': "└",
		'lower_right': "┘",
	},

	'double': {
		'upper_border': "═",
		'lower_border': "═",
		'left_border': "║",
		'right_border': "║",
		'horizontal_line': "═",
		'vertical_line': "║",
		'full_intersection': "╬",
		'left_vertical': "╠",
		'right_vertical': "╣",
		'upper_horizontal': "╦",
		'lower_horizontal': "╩",
		'upper_left': "╔",
		'upper_right': "╗",
		'lower_left': "╚",
		'lower_right': "╝",
	},
	
	'wide': {
		'upper_border': "▄",
		'lower_border': "▀",
		'left_border': "█",
		'right_border': "█",
		'horizontal_line': "▀",
		'vertical_line': "█",
		'full_intersection': "█",
		'left_vertical': "█",
		'right_vertical': "█",
		'upper_horizontal': "█",
		'lower_horizontal': "█",
		'upper_left': "▄",
		'upper_right': "▄",
		'lower_left': "▀",
		'lower_right': "▀",
	},
	
	'dots': {
		'upper_border': ".",
		'lower_border': ".",
		'left_border': ".",
		'right_border': ".",
		'horizontal_line': ".",
		'vertical_line': ".",
		'full_intersection': ".",
		'left_vertical': ".",
		'right_vertical': ".",
		'upper_horizontal': ".",
		'lower_horizontal': ".",
		'upper_left': ".",
		'upper_right': ".",
		'lower_left': ".",
		'lower_right': ".",
	},

	'pluses': {
		'upper_border': "+",
		'lower_border': "+",
		'left_border': "+",
		'right_border': "+",
		'horizontal_line': "+",
		'vertical_line': "+",
		'full_intersection': "+",
		'left_vertical': "+",
		'right_vertical': "+",
		'upper_horizontal': "+",
		'lower_horizontal': "+",
		'upper_left': "+",
		'upper_right': "+",
		'lower_left': "+",
		'lower_right': "+",
	},

	'asterisks': {
		'upper_border': "*",
		'lower_border': "*",
		'left_border': "*",
		'right_border': "*",
		'horizontal_line': "*",
		'vertical_line': "*",
		'full_intersection': "*",
		'left_vertical': "*",
		'right_vertical': "*",
		'upper_horizontal': "*",
		'lower_horizontal': "*",
		'upper_left': "*",
		'upper_right': "*",
		'lower_left': "*",
		'lower_right': "*",
	},
}